# Generated by Django 3.2.18 on 2023-02-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_mst_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_mst_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('email', models.EmailField(default='No mail Specified', max_length=120)),
                ('password', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=11)),
                ('pincode', models.IntegerField()),
                ('referral_code', models.CharField(max_length=10)),
                ('reward_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_executive_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('email', models.EmailField(default='No mail Specified', max_length=120)),
                ('password', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('assigned_pincode', models.IntegerField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise_tbl',
            fields=[
                ('franchise_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('email', models.EmailField(default='No mail Specified', max_length=120)),
                ('location', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=11)),
                ('available_capital', models.FloatField()),
                ('experience', models.CharField(max_length=15)),
                ('save_for_later', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order_tbl',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('is_urgent', models.BooleanField()),
                ('order_status', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('rewarded_discount', models.FloatField()),
                ('net_bill', models.FloatField()),
                ('payment_mode', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer_mst_tbl')),
                ('delivery_executive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery_executive_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='Service_mst_tbl',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=120)),
                ('service_desc', models.CharField(max_length=256)),
                ('price_per_unit', models.FloatField()),
                ('discount_per_service', models.FloatField(default=10)),
                ('urgent_charges', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_tbl',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order_tbl')),
            ],
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service_mst_tbl'),
        ),
        migrations.CreateModel(
            name='Feeback_tbl',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_desc', models.CharField(max_length=256)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('reply_of_feedback', models.CharField(max_length=256)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer_mst_tbl')),
            ],
        ),
    ]
