# Generated by Django 3.2.18 on 2023-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_mst_tbl',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
