# Generated by Django 3.2.18 on 2023-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230311_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_mst_tbl',
            name='service_img',
            field=models.ImageField(default='noimg', upload_to='app/uploads/services'),
        ),
    ]
