# Generated by Django 3.2.18 on 2023-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_service_mst_tbl_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_executive_tbl',
            name='d_adhar_card',
            field=models.ImageField(default='No adhar card', upload_to='app/delivery_executive/addharcards'),
        ),
        migrations.AddField(
            model_name='delivery_executive_tbl',
            name='d_profile',
            field=models.ImageField(default='no profile img', upload_to='app/delivery_executive/profiles'),
        ),
    ]
