# Generated by Django 3.2.18 on 2023-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230315_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_executive_tbl',
            name='gender',
            field=models.CharField(default='Male', max_length=5),
        ),
    ]
