# Generated by Django 3.2.18 on 2023-03-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230315_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_executive_tbl',
            name='d_profile',
            field=models.ImageField(default='no profile img', upload_to='app/static/delivery_executive/profiles'),
        ),
    ]
