# Generated by Django 3.2.18 on 2023-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_delivery_executive_tbl_d_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_executive_tbl',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
