# Generated by Django 3.2.18 on 2023-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_delivery_executive_tbl_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_executive_tbl',
            name='d_adhar_card',
            field=models.ImageField(default='No adhar card', upload_to='media/uploads/delivery_executive/addharcards'),
        ),
        migrations.AlterField(
            model_name='delivery_executive_tbl',
            name='d_profile',
            field=models.ImageField(default='no profile img', upload_to='media/uploads/delivery_executive/profiles'),
        ),
        migrations.AlterField(
            model_name='service_mst_tbl',
            name='service_img',
            field=models.ImageField(default='noimg', upload_to='media/uploads/services'),
        ),
    ]
